// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"time"
)

type Sharedlink struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Urlhash   string    `json:"urlhash"`
	CreatedAt time.Time `json:"created_at"`
}
