// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"
)

type Querier interface {
	CreateSharedlink(ctx context.Context, arg CreateSharedlinkParams) (Sharedlink, error)
	DeleteSharedlink(ctx context.Context, id int64) error
	GetSharedlink(ctx context.Context, id int64) (Sharedlink, error)
	ListSharedlink(ctx context.Context, arg ListSharedlinkParams) ([]Sharedlink, error)
	UpdateSharedlink(ctx context.Context, arg UpdateSharedlinkParams) (Sharedlink, error)
}

var _ Querier = (*Queries)(nil)
